## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#PHPMyAdmin Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_zuul_exam?autoReconnect=true&useSSL=false
    username: root
    password:

##MySQL Config
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring_zuul_exam?autoReconnect=true&useSSL=false
#    username: root
#    password: medisys

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

# Hibernate ddl auto (create, create-drop, validate, update)
# For initital Data Please modify update to create-drop
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9191
  servlet:
    contextPath: /v.0.1/rest